name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['22.0']
        elixir: ['1.12']
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install ImageMagick and FFmpeg
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq imagemagick ffmpeg
      - run: mix deps.get
      - run: mix test
